### ISSUE TITLE
Add another metadata on the injected style tag

### ISSUE THREAD

**Issue by fernandojsg** [cheton/browserify-css#28]
In my code I'm adding styles directly to the html or by using browserify-css. I need to differentiate which ones have been added using browserify-css and they can be dinamic (So I can't query the data-href). Is there any way to add another attribute to <style> so I could detect them?

**Comment by cheton** [comment]
I can add another callback function in the `autoInjectOptions` that allows you to add custom attributes:
https://github.com/cheton/browserify-css/blob/master/index.js#L66

Before doing that, may you provide me a detailed example or use case, so that I will know what parameters are necessary for implementing the callback function.

**Comment by cheton** [comment]
Added a new option `onFlush` in [v0.9.0](https://github.com/cheton/browserify-css/releases/tag/v0.9.0).
Now you can define your metadata by passing a string to the done() callback. For example:

```js
var browserify = require('browserify');

browserify(options)
    .add('src/index.js')
    .transform(require('browserify-css'), {
        rootDir: 'src',
        onFlush: function(options, done) {
            var moduleBody = 'var css = '
                + JSON.stringify(options.data)
                + '; (require(' + JSON.stringify('browserify-css') + ').createStyle(css, { "href": '
                + JSON.stringify(options.href)
                + '})); module.exports = css;';

            done(moduleBody);
        }
    })
    .bundle();
```
